name = "SDFResultViewer"
uuid = "7a8fc443-14dd-4e51-a296-5a2c4c9a1dbb"
authors = ["Sebastian Micluța-Câmpeanu <m.c.sebastian95@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
EPOCHInput = "691e61f8-6502-44a1-a143-5276a0aa0dc4"
FileTrees = "72696420-646e-6120-6e77-6f6420746567"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
JSServe = "824d6782-a2ef-11e9-3a09-e5662e0c26f9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
PICDataStructures = "cb18667b-f199-4b8b-b886-9916fef47a26"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SDFResults = "3e51950c-1d7d-41c0-8bda-2201d9a6ffd5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulRecipes = "42071c24-d89e-48dd-8a24-8a12d9b8861f"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
ArrayInterface = "2.14, 3.0"
EPOCHInput = "0.1"
FileTrees = "0.1"
ImageTransformations = "0.8"
IntervalSets = "0.5"
JSServe = "1.2"
NumericalIntegration = "0.3"
PICDataStructures = "0.1"
PhysicalConstants = "0.2"
Plots = "1.10"
RecursiveArrayTools = "2.7"
SDFResults = "0.1"
StaticArrays = "1.0"
ThreadsX = "0.1"
Transducers = "0.4"
Unitful = "1.5"
WGLMakie = "0.3"
julia = "1.5, 1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
