name = "SDFResultViewer"
uuid = "7a8fc443-14dd-4e51-a296-5a2c4c9a1dbb"
authors = ["Sebastian Micluța-Câmpeanu <m.c.sebastian95@gmail.com> and contributors"]
version = "0.2.0"

[deps]
JSServe = "824d6782-a2ef-11e9-3a09-e5662e0c26f9"
LaserTypes = "e07c0bfa-524c-4f35-a151-c3dd916fa2f0"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PICAnalysisTools = "049d77de-c438-40ac-b6d1-f1d179569bd2"
PICDataStructures = "cb18667b-f199-4b8b-b886-9916fef47a26"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SDFResults = "3e51950c-1d7d-41c0-8bda-2201d9a6ffd5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
JSServe = "1.2"
LaserTypes = "0.1"
PICDataStructures = "0.3"
PhysicalConstants = "0.2"
Plots = "1.10"
ProgressLogging = "0.1"
PyPlot = "2.9"
Rotations = "1.0"
RecursiveArrayTools = "2.11"
SDFResults = "0.1"
StaticArrays = "1.1"
StatsBase = "0.33"
Unitful = "1.5"
WGLMakie = "0.3"
julia = "1.5, 1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
